import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MyThemeContextProvider } from "@/components/store/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark:bg-gray-900">
      <MyThemeContextProvider>
        <body className="dark:bg-gray-900">
          <Navbar></Navbar>
          <hr></hr>
          {children}
        </body>
      </MyThemeContextProvider>
    </html>
  );
}
